insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'AD', 'Andorra');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'AE', 'Emirados Árabes Unidos');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'AF', 'Afeganistão');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'AG', 'Antígua e Barbuda');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'AI', 'Anguilla');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'AL', 'Albânia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'AM', 'Armênia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'AO', 'Angola');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'AQ', 'Antártica');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'AR', 'Argentina');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'AS', 'Samoa Americana');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'AT', 'Áustria');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'AU', 'Austrália');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'AW', 'Aruba');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'AZ', 'Azerbaijão');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BA', 'Bósnia e Herzegovina');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BB', 'Barbados');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BD', 'Bangladesh');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BE', 'Bélgica');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BF', 'Burkina Faso');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BG', 'Bulgária');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BH', 'Barém');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BI', 'Burundi');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BJ', 'Benin');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BL', 'São Bartolomeu');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BM', 'Bermuda');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BN', 'Brunei');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BO', 'Bolívia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BR', 'Brasil');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BS', 'Bahamas');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BT', 'Butão');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BV', 'Ilha Bouvet');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BW', 'Botswana');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BY', 'Belarus');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'BZ', 'Belize');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CA', 'Canadá');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CC', 'Ilhas Cocos (Keeling)');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CD', 'Congo, República Democrática do');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CF', 'República Centro-Africana');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CG', 'Congo, República do');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CH', 'Suíça');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CI', 'Costa do Marfim');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CK', 'Ilhas Cook');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CL', 'Chile');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CM', 'Camarões');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CN', 'China');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CO', 'Colômbia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CR', 'Costa Rica');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CU', 'Cuba');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CV', 'Cabo Verde');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CW', 'Curaçao');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CX', 'Ilha Christmas');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CY', 'Chipre');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'CZ', 'República Tcheca');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'DE', 'Alemanha');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'DJ', 'Djibuti');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'DK', 'Dinamarca');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'DM', 'Dominica');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'DO', 'República Dominicana');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'DZ', 'Argélia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'EC', 'Equador');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'EE', 'Estônia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'EG', 'Egito');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'EH', 'Saara Ocidental');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'ER', 'Eritréia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'ES', 'Espanha');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'ET', 'Etiópia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'FI', 'Finlândia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'FJ', 'Fiji');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'FK', 'Ilhas Falkland (Malvinas)');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'FM', 'Micronésia, Estados Federados da');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'FO', 'Ilhas Feroe');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'FR', 'França');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'FX', 'França Metropolitana');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GA', 'Gabão');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GB', 'Reino Unido');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GD', 'Grenada');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GE', 'Geórgia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GF', 'Guiana Francesa');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GG', 'Guernsey');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GH', 'Gana');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GI', 'Gibraltar');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GL', 'Greenland');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GM', 'Gâmbia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GN', 'Guiné');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GP', 'Guadelupe');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GQ', 'Guiné Equatorial');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GR', 'Grécia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GS', 'Geórgia do Sul e Ilhas');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GT', 'Guatemala');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GU', 'Guam');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GW', 'Guiné-Bissau');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'GY', 'Guiana');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'HK', 'Hong Kong');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'HM', 'Ilhas Heard and McDonald');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'HN', 'Honduras');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'HR', 'Croácia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'HT', 'Haiti');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'HU', 'Hungria');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'ID', 'Indonésia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'IE', 'Irlanda');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'IL', 'Israel');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'IM', 'Ilha de Man');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'IN', 'Índia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'IO', 'Território Britânico do Oceano Índico');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'IQ', 'Iraque');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'IR', 'Irã');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'IS', 'Islândia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'IT', 'Itália');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'JE', 'Jersey');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'JM', 'Jamaica');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'JO', 'Jordânia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'JP', 'Japão');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'KE', 'Quênia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'KG', 'Quirguistão');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'KH', 'Camboja');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'KI', 'Kiribati');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'KM', 'Cômoros');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'KN', 'São Cristóvão e Nevis');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'KP', 'Coreia do Norte');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'KR', 'Coreia do Sul');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'KW', 'Kuwait');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'KY', 'Ilhas Caiman');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'KZ', 'Cazaquistão');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'LA', 'Laos');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'LB', 'Líbano');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'LC', 'Santa Lúcia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'LI', 'Liechtenstein');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'LK', 'Sri Lanka');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'LR', 'Libéria');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'LS', 'Lesoto');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'LT', 'Lituânia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'LU', 'Luxemburgo');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'LV', 'Letônia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'LY', 'Líbia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MA', 'Marrocos');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MC', 'Mônaco');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MD', 'Moldova');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'ME', 'Montenegro');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MF', 'Saint Martin');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MG', 'Madagascar');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MH', 'Ilhas Marshall');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MK', 'Macedônia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'ML', 'Mali');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MM', 'Birmânia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MN', 'Mongólia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MO', 'Macao');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MP', 'Ilhas Marianas do Norte');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MQ', 'Martinica');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MR', 'Mauritânia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MS', 'Montserrat');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MT', 'Malta');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'mu', 'Ilhas Maurício');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MV', 'Maldivas');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MW', 'Malawi');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MX', 'México');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MY', 'Malásia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'MZ', 'Moçambique');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'NA', 'Namíbia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'NC', 'Nova Caledônia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'NE', 'Níger');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'NF', 'Ilha Norfolk');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'NG', 'Nigéria');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'NI', 'Nicarágua');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'NL', 'Holanda');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'NO', 'Noruega');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'NP', 'Nepal');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'NR', 'Nauru');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'NU', 'Niue');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'NZ', 'Nova Zelândia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'OM', 'Omã');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'PA', 'Panamá');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'PE', 'Peru');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'PF', 'Polinésia Francesa');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'PG', 'Papua Nova Guiné');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'PH', 'Filipinas');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'PK', 'Paquistão');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'PL', 'Polônia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'PM', 'Saint Pierre e Miquelon');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'PN', 'Ilhas Pitcairn');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'PR', 'Porto Rico');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'PS', 'Faixa de Gaza');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'PS', 'Cisjordânia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'PT', 'Portugal');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'PW', 'Palau');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'PY', 'Paraguai');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'QA', 'Qatar');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'RE', 'Reunião');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'RO', 'Romênia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'RS', 'Sérvia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'RU', 'Rússia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'RW', 'Ruanda');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SA', 'Arábia Saudita');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SB', 'Ilhas Salomão');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SC', 'Seicheles');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SD', 'Sudão');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SE', 'Suécia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SG', 'Cingapura');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SH', 'Santa Helena, Ascensão e Tristão da Cunha');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SI', 'Eslovênia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SJ', 'Svalbard');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SK', 'Eslováquia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SL', 'Serra Leoa');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SM', 'San Marino');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SN', 'Senegal');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SO', 'Somália');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SR', 'Suriname');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SS', 'Sudão do Sul');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'ST', 'São Tomé e Príncipe');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SV', 'El Salvador');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SX', 'São Martinho');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SY', 'Síria');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'SZ', 'Suazilândia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TC', 'Ilhas Turks e Caicos');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TD', 'Chad');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TF', 'Sul da França e Antártica');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TG', 'Togo');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TH', 'Tailândia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TJ', 'Tadjiquistão');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TK', 'Toquelau');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TL', 'Timor-Leste');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TM', 'Turcomenistão');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TN', 'Tunísia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TO', 'Tonga');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TR', 'Turquia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TT', 'Trinidad e Tobago');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TV', 'Tuvalu');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TW', 'Taiwan');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'TZ', 'Tanzânia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'UA', 'Ucrânia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'UG', 'Uganda');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'UM', 'Ilhas Menores Distantes dos Estados Unidos');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'US', 'Estados Unidos');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'UY', 'Uruguai');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'UZ', 'Uzbequistão');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'VA', 'Santa Sé (Cidade do Vaticano)');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'VC', 'São Vicente e Granadinas');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'VE', 'Venezuela');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'VG', 'Ilhas Virgens Britânicas');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'VI', 'Ilhas Virgens Americanas');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'VN', 'Vietnã');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'VU', 'Vanuatu');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'WF', 'Ilhas Wallis e Futuna');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'WS', 'Samoa');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'XK', 'Kosovo');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'YE', 'Iêmen');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'YT', 'Maiote');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'ZA', 'África do Sul');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'ZM', 'Zâmbia');
insert into Country (Id, RegisterDate, LastChangeDate, Status, Initials, Name) values (NEWID(), GETDATE(), GETDATE(), 0, 'ZW', 'Zimbábue');